# Generated by Django 3.0.3 on 2020-02-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_comments_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
