# Generated by Django 3.0.3 on 2020-02-13 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200213_0346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
