# Generated by Django 3.0.3 on 2020-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200213_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='screenshot_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
