# Generated by Django 3.0.3 on 2020-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_detail_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='github',
            field=models.URLField(default='', max_length=100),
        ),
    ]
